### ISSUE TITLE
getenv questions inconsistent with rest

### ISSUE THREAD

**Issue by sirblackheart** [sirblackheart/elektrasurvey#5] opened 2016-06-01 11:36 UTC

**Comment by Namoshek** [comment] 2016-06-01 18:27
We are still using two answers consisting of full sentences and only phrases for the others, that doesn't look consistent. If you think it's ok, close the issue, I can live with it, just wanted to point it out.

**Comment by markus2330** [comment] 2016-06-01 18:41
you are right, the problem is that it is an question asking multiple (nearly unrelated) questions.
I will think about it.

**Comment by markus2330** [comment] 2016-06-01 19:45
getenv "I do not use it (use other to write why)" blocks "other"

**Comment by markus2330** [comment] 2016-06-01 19:56
I updated it in 978550d9e6cbb8c72dd963c809f48df5d00d2428
It should be now much more consistent.

please also fix the blocking of "other"

**Comment by Namoshek** [comment] 2016-06-01 20:14
Please see my note in the commit. I changed it to what I think is meant. I also removed the exclusive answer feature so that other can always be filled, but that also means that "I do not" does not disable the other answers anymore.

**Comment by markus2330** [comment] 2016-06-01 20:24
looks ok, you can close it

**Closed** 2016-06-01 20:26 UTC
