### ISSUE TITLE
make "Which configuration systems..." easier

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#78] opened 2016-06-07 19:45 UTC
Eine Antwortmoeglichkeit wie "I don't know what this is" fuer die Frage "Which configuration systems/libraries/APIs have you already used or would like to use in one of your projects? " waere vielleicht auch von Interesse, weil ja nicht jeder alles kennen muss.

**Comment by sirblackheart** [comment] 2016-06-07 20:04
duplicate of #56

**Comment by markus2330** [comment] 2016-06-08 07:34
The person repeats a good point: we are somehow implying you know the systems, which is not a good thing if we want non-expert participants to go through all questions.

So we could either change "have not used" or add a new option.

I think it would hardly have any effect on the answers we get: the differences between having no contact with something, not using it, never heard of it, and not knowing it are not really important for us.

And if the "do not know it" has some "feel-good factor" and makes participant feel they are the right ones for this survey, we should go for it.

So I would suggest "have not used" ->

1. "do not know it"
2. "never heard of it or used it"
3. "never had contact"

What do you think?

**Comment by sirblackheart** [comment] 2016-06-08 08:21
Is there a reason to open a closed for duplicate instead of using the other issue for the discussion?

**Closed** 2016-06-08 08:33 UTC

**Comment by markus2330** [comment] 2016-06-08 08:59
Yes, there was, the other issue was a discussion of hints "when to use NA" not about engaging non-experts by changing the text even though its logical implied. But its not important, let us continue the discussion there.

**Comment by sirblackheart** [comment] 2016-06-08 09:04
No the base feedback of issues is the same.
The suggestion of adding hints was a possible solution.
As is the changing of the text so solve the problem.
